image: docker-registry.int.protectwise.net:5000/pw_docker_python:latest

stages:
    - build
    - deploy

build_and_deploy_package:
  only: [master]
  stage: build
  tags:
    - docker
  script:
    - sudo python3.5 -m pip install .
    - python3.5 -m pip install setuptools
    - sed -i -E -e "s/PATCH_VERSION = [0-9]+/PATCH_VERSION = ${CI_BUILD_ID}/" setup.py
    - python3.5 setup.py bdist_wheel
    - python3.5 -m pip install devpi-client==2.6.2 pyyaml
    - python3.5 -m devpi use http://devpi.int.protectwise.net/pw/dev
    - python3.5 -m devpi login pw --password=pw
    - python3.5 -m devpi upload dist/*
    - python3.5 -m devpi use http://devpi.int.protectwise.net/pw/prod
    - python3.5 -m devpi upload dist/*
    - python3.5 -m devpi use http://devpi.int.protectwise.net/pw/staging
    - python3.5 -m devpi upload dist/*
