default_stages: [commit]
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-ast
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [--config=black.toml]
        language_version: python3
