dist: xenial
language: python
python:
- '3.7'
script:
- python3 setup.py test
- python3 setup.py sdist bdist_wheel
deploy:
  provider: pypi
  on:
    branch: master
    tags: true
  user: cybergrx
  password:
    secure: AR7SNcv/U674C7WXIrts8omt/3D48ZWEtg892D4NsczElCG118kR3Vat4pBqmNtcdj/xL9XUmRjoSDJ+EBZx/YYpDHttO4vzQRLIfeQ5almA5uQBmmy/GlZf06hUdriBeEZULPfcnGS9CDC1ZZug6WQ48rxrBdtIhQ1rIdOTWJFG1K8xzh1j8WoUtEdMSHkANsdyv+qfP3joRLr0LG4Quaz7ioOMhtHBfsqo5o4rZ3CQT43DZoQYiyA+Z31igdbO51Li13x+3+KaHr00S0ksTE4NqibwG0wGeoxIBOI/Sv1WiY3NmMc905pcBtt/rtTFG0oBrHcLgBlKuZ74HI7uwfmSEe/A4NnOTw9vnKyDJ8H0QpHfg+fDTAqF4j/9x02LOUtO+BwMZxv1QYfJL6L1fSf+FONh7pdi9uUNukTzAQFifUhCWxnSp+2yDPmT0Pcz4WAjyqFqSMnp+9WtVjMkdH6OClReWHfnsWzS0rgEJXlrDHjzFdWrt90xmdnhurzqrsF18m7DruHw5aV9rflgPloj50Gugq9R2qAvSMSfKbISPyLnwPd8zkBMBao1VLh7sqz/+CG+04i/fbLfWyWuWC1Omigp7YMh0JWL9QCBWuMfCiLAOaow/VIuVqZVfJbWGhJbDiGK0XcCOsgFIwqw9oDt8ugvX8MEuL8exYcvpvI=
