dist: xenial
language: python
python:
- '3.7'
script:
- python3 setup.py test
- python3 setup.py sdist bdist_wheel
deploy:
  provider: pypi
  on:
    branch: master
    tags: true
  user: cybergrx
  password:
    secure: Uo/P49lbh27I1pf2r4nKjsivUGzOI3LXXGuMrsWUw63HggoKrKYrDL0+bTaxXIlNCc5ygvPJO1UH59VC6KNk729zdmGRCoZdawgBGAgLGBGE2+CIa54RQFfDqqNpXJbMym3BtSUCgtE3AU+iRxbeVI/Yojj3+Ey8RD1s+7X0MD9/X9kZxPS+anK/IZ7YTygjd0q+vj33UUOj7nn8wstFGSPEdMLOZY1+BFMqCySn4kTjTpR3VMUQVE6c/Y+UoRIw0CTKq8kd/V1GPN4LGpVmvRGIy+deujJ4ip1u02MNZoaRkKvrafnFuYCmGxNa8T8OxSIRY4p2X9/vwXPfL3EwPjL7Xx65hWYWHoya42O/3LvEM1TjHiqsJYAy7ae/ttzmeVHwQGR0OLMeUmzhNuC0RP7f4ANB9beFGoploPYi/Dy/vr2vgqUNYz0l33sGhNMfVF/YyuOR4qUSw6Wogdz7OiIT66LxZXfZdtmSQN4q/OO+9gnv0ZUB9phiOD/AhdkSK3Mn6hdAL4R/YOqWG8eRdBOQlcikeJQd4vWSp8sv7VKkbfKpVQVWgyHDV/65zsNDt7G49XSV8E0k2Cc9U2xejM0tPoyUnGnTHltIGcEMQ2IFjJbkWq8SIBUi+Uk/T7prVaBDfjkylBcdY7puwJlLSwhTankvpBUZQO7dQsQtBME=
