dist: xenial
language: python
python:
- '3.7'
script:
- python3 setup.py test
- python3 setup.py sdist bdist_wheel
deploy:
  provider: pypi
  on:
    branch: master
    tags: true
  user: cybergrx
  password:
    secure: Y+kU0qVSHWx9O1B+pZKNz7dB2RsuHSigA61P3hl7Z3O9AxXbAB0A1N3ZSeRkx5pjSdwjaz52sJhGOfh3Cs6wyYUheoUKbVL27lKp1QXz3mETurgyEfUIXyl6sTjcDa0dseaaJJ/vpkgo8sJviZPE5S8R+PmCWo95rwlwTZkoxsMy/WUM/dFsJf7TxQMDPdkF+Qq5IU7SGl03koEK5xrja1jIf1HfR53eXrBiP+9B3KNEeQb9OoexCHimy9w6ikzpDAOEFMVBO6MVgaVwb5YG2yDgxH/xSBteoC9IwXOck9OKOWbi7pxcZ9HmxMz2YTl6p7WXLEb0x+qOrUjEyaXZXEfeHGzCq927N3cn4mFlCbHligiAQMtJbA8JZj0HC6dsYAsg0BPe9nBOWtGAPVk31Yqc5RxzH+xwM4NmY6NnDJ0kdE6bZqm8+zl2xIR5cSkjQ4hlZXLp3BcUba0VTWxtsyqbbnRqt+7FF/l2ftPKELyPQ6PE7OUQwkF5HBHnsSgyrs6IUxJ32mTCIba6nMbd5hDAHEA1o9tytUgsjvB7M/NQvuFRVrpEa0a16BSIzolIpPYdzmvpsC9c6dOWXM+w1JhmMq8EoplYlpDOenmychPYy5wf0oHvqYIBTTZIA5/bx+2xrXCAXmEaq6VRHBZ6tCsjYslDL/huOqsx9ypJRII=
