dist: xenial
language: python
python:
- '3.7'
script:
- python3 setup.py test
- python3 setup.py sdist bdist_wheel
deploy:
  provider: pypi
  on:
      branch: master
      tags: true
env:
  global:
  - secure: JrXKj/82+g5Kvn58sVXOEBVZy4tfvMqPX/kheA+zY/DENe/NEw1FRsPI1eyxcvDmx9ZLKm+CFd9fzPUWa3mzVNZbcmrVHhN24pweZfccOXgQJ3jihLjZpemSRkTrwNqLHZeH+zaC9ABfwW4zVRhke8zkCgSkw3E2hzidz4O5FAP69Qf2qElyFQ5F7zesa24vctSsIbVv9jkzDBzFfFjceXoGLacG1rNtVt647FDZSFUckrgUVJB3agJJjYMxJuoPqK7V5eLQpWWFfPPwoMNDypy6ebmzPuG3DpsvWDXblV+Dmg+EraQXpquGvAGjR1TaSAR9I1YEEOvs3r/ygYYDuvmg9GUjsWlzjYndGIlkEO3a9JjmdQUb10eZWkCxHVnR4aaZfEPRRnRpt0KP+WlHSnmoQDS3UNUOLLsxNCjDN5ANtroBaFC+CGNs60CKLwAn/zvJiLlepcAlm7VIgKwYnGFT206VzwYvMfaezym6+DabbMq+PnbMV3k8n4G/a8kWVhcv3rWvvWJ+emSUMlkEldH/IHhtPgOJAIAQWV15nmZsr32qFi6Q0OxcJNpnc1gnGIO/cP6X7GzCi9W4pnv72HpjV0QcMpeLtuVu560L+9JVpMVuN8DluDSYt5v7a83kbmjCtaklyjxVh4SrVdfoZgVg4swifhAU4x/jb64lzQ4=
  - secure: UYxif8Bn4bjXlwiNKT3o3N6GeS7WGRo6Salku3VRDmLvBaRtNZP33fpfbgu37742t4JKQF2hkzaUFqt9+MTQc4rt2TkwZICt/AZnPtT/GQ74nhYVbfDt6CYGu+lqYTyIrPQMghpcJRcC4kqQyThHr3u5ylyE//1sa6bW6G8NE29DuZ3aW7F8T0tniEQ7HoZJkeJ47QayqAUI3OOizuMIy2vio7vnFb/9xuoRP4BOfHrLPVFCwmxt+X/D7cpxniqgPaxYMUnv/5HkUqt3QgdVRaZsxd2vBHbX1GHxZxKhKK57FYA1/Z745/x2nqFcznZ52qBZz5fZJwijSjwq+WlDr/wOHfpAfpM7vUqQdyjv87zmfymbhqsSh39OQ5nTeJEuHZZaR9SNnJ/2xF7BQmAYKFpPAZa7dDrMxMDWF9QzZ2m3m6obwEK/P8P1fGHBxZDrtkKpJtw5gJrdlyFziOvjcLCVkHzxmbkOFZ9EgVZzj8EqmrpdzNgGxB3V7NFLcaehyZR1Uj4av7yFw/SgDgcQIoVCxG0Uz9zR2nqingQ4x/FLXrhZwUQ2prU12yNkaPgxqTsQfHJZP6QJF8Va41/1uljh5Bq/mup/FOshTVooI7mxuhzKurezTigA2KUYfTJN65/yH9r+6YTSx782KFO+pOT+6qwydwBERS0cbOAlP9c=
