dist: xenial
language: python
python:
- '3.7'
script:
- python3 setup.py test
- python3 setup.py sdist bdist_wheel
deploy:
  provider: pypi
  on:
    branch: master
    tags: true
  user: cybergrx
  password:
    secure: gXg3VE2ZOzS5r45mtfKnTx5CEDueQpjczQ0yvmpJZA+ck5UInPbpBWzVFkS/iU3e2Gb3s3fonE1QwPu+bFGumcuzBoYCC3WRw16mx3ZyPXp7rZJLvkq9zIzANCebX9yPEWA1Y1jOOcZA+ri+fmwKKGRaMIUPRvjn2kGFTfIc0komLju/YSwCKW10BRyXj7Kzn86fT60vgIXgkGi/TNCg+DqDCZhFHkxXVe+D9aXkXX4XA65uSEHiXLcOChXCeBcKlpEx4dilxU8OGkDPcnWD9IhorK7Bkx0xSlmlNdCTkKVjyaD2/AMekPiJTWJE3IZzXHl+wwjzvYZN/v1A1tTFMyO0bc/rruwg1yBaiyqSwyDo5iQEXQhN/PGvUvu0Weh+FpjVSMGJgvaCAiNKki2BsYvMM3BpYPVV5VT9XjBz5MH0bmFvj8Xkozy+XjTOkJUVR65u59Vnz28tGH/0S1DEf8ytPlO4jHTTFhsrmeyoqlq6ZOrxssDW2dQ2zfaM/FrxRyR4MVnuvt9zLvmQViUDizIukF5pOJ/3M9s5Y2qrwFR9vhUuk30I84gRvHN7+gwKgdYvccO4vDGInpw64SPFatzNxA3Uk26cVjf8DsQveM3e++fCFcxI5K5uSWytTUhg34nhKY9m/QvUqRpgiAxFVopOlz9dvanK9Wl9FZ/Z9qY=
