dist: xenial
language: python
python:
- '3.7'
script:
- python3 setup.py test
- python3 setup.py sdist bdist_wheel
deploy:
  provider: pypi
  on:
    branch: master
    tags: true
  user: cybergrx
  password:
    secure: JXrVNdtL5tnNkDht8AYl3d+KtsJWfU7s7OacSknYR8a7aXrbOjFT2qIbp9MS+OGmMMzTCbWP3ISMLkpqOFi9z9VvsLRTvDoO6e5L0tkrYxRtGhEWvjmgjx7yMnKarKvqD+iC05vgzoXyvRqQVd/3PANhPqQwsa5rZA2ZZWkQVZWmFd47wySHclb/gaH/q5xDMY3yVJqyOuDwa/nRerz8LnWQQ35jtzChmvNIX9GfE3GoH2QyC6A9iSXFEo4QRD8ubcqzJAofgIRyAPzJceAY3//opqjvOi579fKcNKrS8llczgSMB6SP3J1JDJcUx/gAb/Oi4hGVpFE7e1O5KRAqlxYazpkHL5Z2c11UH89Cbob5aUYhSdmoQ+EBymVwBDsSZcjSpGOPzylqLGvic9Qial2I98uwcfocTe5tvuOLnZvC2TIDMwZVAgMpcO77Dpf8ObKznffx6dWovt/3EuQtMZEmbKCxDUbVH2/yfmGSdZlZ6Y6yFZHWUnPvqhr7a+Ln6wUzoA716U6P0Wead/eno6ccxPmQRnavhurGqlgzz03FLVmGWhytYmG6NitHZE7OnRjNBHd+JhOUrmdIynwhPZD+K5Te1WN2CHplZkUbQFCSx5DWU/c9Bcl+aMrWYEMSwsqGprlPqQbJMk4Cv3PNhsobvHj0w4gWdkfZ9vzEb+w=
